from .auth_errors import AuthenticationError